version: '3.9'
services:
  app:
    # build:
    #   args:
    #     USER: ${USER:-0}
    #     USER_ID: ${USER_ID:-0}
    #     GROUP_ID: ${GROUP_ID:-0}
    #   context: .
    #   dockerfile: Dockerfile
    image: l1th1um/laravel-php-81:1.1
    container_name: news_agg-app
    image: news_aggregator
    volumes:
      - ../www:/var/www/
    networks:
      - news_agg_network

  supervisor:
    build:
        context: .
        dockerfile: supervisor.dockerfile
    container_name: news_agg-supervisor
    volumes:
      - ../www:/var/www/
    networks:
      - news_agg_network
  db:
    image: mysql:8.4
    container_name: news_agg-mysql
    command: --mysql-native-password=ON
    volumes:
      - ${HOME}/docker_data/news_agg/mysql_data:/var/lib/mysql
    ports:
      - 33070:3306
    environment:
      MYSQL_DATABASE: news_agg
      MYSQL_ROOT_PASSWORD: rahasia
    networks:
      - news_agg_network
  redis:
    image: redis:7.0-alpine
    container_name: news_agg-redis
    ports:
      - 63791:6379
    networks:
      - news_agg_network
  nginx:
    image: nginx:alpine
    container_name: news_agg-nginx
    ports:
      - 80:80
    volumes:
      - ../www:/var/www/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - news_agg_network

networks:
  news_agg_network:
    driver: bridge
